### ISSUE TITLE
Add doc about thorntail.io usage

### ISSUE THREAD

**Issue by cchet** [mp911de/logstash-gelf#154]
This logging implementation works with thorntail.io as well, and can be useful to developers which are bound to graylog, and cannot use thorntail.io supported logstash.

**The following configuration is needed to get it running with thorntail:**

src/main/resources/modules/biz/paluch/logging/main/module.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="biz.paluch.logging">
    <resources>
        <artifact name="biz.paluch.logging:logstash-gelf:1.11.2" />
        <artifact name="redis.clients:jedis:2.9.0" />
        <artifact name="org.apache.commons:commons-pool2:2.4.3" />
    </resources>

    <dependencies>
        <module name="org.apache.log4j" />
        <module name="org.slf4j" />
        <module name="javax.api" />
        <module name="org.jboss.logmanager" />
    </dependencies>
</module>
```

src/main/resources/project-stages.yml:
```yaml
swarm:
  logging:
    custom-handlers:
      GELF-HTTP:
        attribute-class: biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler
        module: biz.paluch.logging
        properties:
          host: http://[host]:[port]/gelf
    root-logger:
      level: INFO
      handlers:
        - GELF-HTTP
```
