### ISSUE TITLE
Doc for wildfly-swarm (throntail) is wrong

### ISSUE THREAD

**Issue by cchet** [mp911de/logstash-gelf#191]
The doc for throntail displays properties in the format **key=value**, but this should be **key: value**

```
swarm:
  logging:
    custom-handlers:
      GelfLogger:
        attribute-class: biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler
        module: biz.paluch.logging
        properties:
            host=udp:localhost
            port=12201
            version=1.0
            facility=java-test
            extractStackTrace=true
            filterStackTrace=true
            includeLocation=true
            mdcProfiling=true
            timestampPattern=yyyy-MM-dd HH:mm:ss,SSS
            maximumMessageSize=8192
            additionalFields=fieldName1=fieldValue1,fieldName2=fieldValue2
            additionalFieldTypes=fieldName1=String,fieldName2=Double,fieldName3=Long
            MdcFields=mdcField1,mdcField2
            dynamicMdcFields=mdc.*,(mdc|MDC)fields
            includeFullMdc=true
    root-logger:
      level: INFO
      handlers:
      - GelfLogger
```

but they should be like this, because its YAML we use here

```
swarm:
  logging:
    custom-handlers:
      GelfLogger:
        attribute-class: biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler
        module: biz.paluch.logging
        properties:
            host: "udp:localhost"
            port: 12201
            version: 1.0
            facility: "java-test"
            extractStackTrace: true
            filterStackTrace: true
            includeLocation: true
            mdcProfiling: true
            timestampPattern: "yyyy-MM-dd HH:mm:ss,SSS"
            maximumMessageSize: 8192
            additionalFields: "fieldName1=fieldValue1,fieldName2=fieldValue2"
            additionalFieldTypes: "fieldName1=String,fieldName2=Double,fieldName3=Long"
            MdcFields: "mdcField1,mdcField2"
            dynamicMdcFields: "mdc.*,(mdc|MDC)fields"
            includeFullMdc: true
    root-logger:
      level: INFO
      handlers:
      - GelfLogger
```
